# Generated by Django 3.1.3 on 2021-01-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20210111_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rank',
        ),
    ]
